Develop: week
yuehhsin/taipei-day-trip-website pull request #3
Opened 2021-05-01 02:51 UTC by yuehhsin

高悅心~
http://3.129.202.152:3000/
作業再麻煩老師了,謝謝.

2021-05-01 03:58 UTC, cwpeng requested changes
小的螢幕 360px 版面會超出去
![3 129 202 152_3000__keyword=%E6%AD%A5%E9%81%93](https://user-images.githubusercontent.com/6104683/116770237-93f27200-aa74-11eb-8da7-dfb11e26dccd.png)

2021-05-01 08:32 UTC, yuehhsin commented
高悅心
http://3.129.202.152:3000/
作業已修正!再麻煩老師了,謝謝~

2021-05-01 15:03 UTC, cwpeng approved these changes
OK 哦，做得很不錯，這樣就可以了 :)

不過有 Git 版本衝突的問題，你得試著解決才有辦法 Merge Pull Request 哦 ~

2021-05-04 07:29 UTC, cwpeng commented
記得要把第二周的 Pull Request Merge 哦，還有個版本衝突要解決 ~

2021-05-04 08:33 UTC, merged

2021-05-04 08:34 UTC, yuehhsin commented
> 記得要把第二周的 Pull Request Merge 哦，還有個版本衝突要解決 ~

謝謝老師的提醒> < 剛剛merge完了!