Develop: week04
yuehhsin/taipei-day-trip-website pull request #5
Opened 2021-05-12 09:48 UTC by yuehhsin

老師我來交作業了👋

高悅心 
http://3.129.202.152:3000/
http://3.129.202.152:3000/attraction/200

2021-05-12 19:26 UTC, cwpeng requested changes
我測試的時候遇到許多問題如下：
1. 註冊表單的按鈕記得改字。
2. 密碼的欄位請用密碼輸入框處理。
3. 輸入相同的 Email 註冊，雖然後端會阻擋，但前端會一直顯示註冊成功。
4. 若登入一次失敗，第二次就算輸入成功似乎也無法成功進行登入。

可能還有很多小問題，建議自己測試的時候不要只想一個正常的流程，應該要反覆測試各種可能性。例如註冊成功、重複註冊、登入、登出、登入輸入錯誤，登入輸入正確，這樣各種情境來確認。

2021-05-13 09:37 UTC, yuehhsin commented
老師下午好~
我真的太粗心了,bug一大堆😱
目前我盡可能的測試修正了,再麻煩老師檢查了🙇‍♀️

高悅心
http://3.129.202.152:3000/
http://3.129.202.152:3000/attraction/200

2021-05-13 16:23 UTC, cwpeng requested changes
有改善很多哦，畫面也都不錯。

不過還有一個問題，你的登出程式，沒有確保在後端完成之後才執行 reload()，所以有時候會登出失敗。前端的 JavaScript 可以確保後端登出的動作執行完成才進行 reload()，程式稍微小小修正即可，但背後是很重要的觀念，所以請你研究一下修正完再和我說 ~

2021-05-14 02:11 UTC, yuehhsin commented
老師我修正完了!👋👋👋

高悅心
http://3.129.202.152:3000/
http://3.129.202.152:3000/attraction/200

2021-05-14 04:13 UTC, cwpeng approved these changes
好哦，這樣就可以了 :)

2021-05-18 10:06 UTC, merged